#!/bin/sh
# Headscale s6 service

# Signal readiness to CIT once the control server answers
s6-ready-when fetch -qo /dev/null http://localhost:8080/health

exec /usr/local/bin/s6-setuidgid bsd /usr/local/bin/headscale serve -c /config/config.yaml
